import type { Metadata } from "next";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import { WalletProvider } from "./context/WalletContext";

export const metadata: Metadata = {
	title: "BitGifty",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<ChakraProvider>
					<WalletProvider>{children}</WalletProvider>
				</ChakraProvider>
			</body>
		</html>
	);
}
